[package]
name = "matcher"
version = "0.1.0"
authors = ["Vadim Kaushan <admin@disasm.info>"]
edition = "2018"

[dev-dependencies]
criterion = "0.2.11"

[[bench]]
name = "target_benchmark"
harness = false

[profile.release]
debug = true
